### ISSUE TITLE
Error trying to add a new remote metastore

### ISSUE THREAD

**Issue by mroark1m** [ExpediaGroup/apiary-federation#36]
I add the new metastore to the remote_metastores list (in this case going from 2 metastores to 3 metastores), but running plan or apply yields: 

```
Error: Error refreshing state: 1 error(s) occurred:

* module.apiary-federation.data.template_file.remote_metastores_yaml: 1 error(s) occurred:

* module.apiary-federation.data.template_file.remote_metastores_yaml[2]: index 2 out of range for list data.external.endpoint_dnsnames.*.result (max 2) in:

${lookup(data.external.endpoint_dnsnames.*.result[count.index],"dnsname")}
```

**Comment by mroark1m** [comment]
One workaround seems to be to target the new remote metastore first, by adding this to the plan/apply run on the first try:

`-target=module.apiary-federation.aws_vpc_endpoint.remote_metastores[2]`

then run apply again without a target.

**Comment by mroark1m** [comment]
@rpoluri said:

> we might need to add explicit dependency on endpoint service here https://github.com/ExpediaInc/apiary-federation/blob/master/endpoints.tf#L48

**Comment by mroark-exp** [comment]
Getting a similar error today, but I havent' changed anything in my config... but there is a difference, it's not failing on the same part of the config:


```
<prior output skipped>
data.external.endpoint_dnsnames[1]: Refreshing state...
data.external.endpoint_dnsnames[0]: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* module.apiary-federation.data.external.endpoint_dnsnames: 1 error(s) occurred:

* module.apiary-federation.data.external.endpoint_dnsnames[2]: index 2 out of range for list aws_vpc_endpoint.remote_metastores.*.id (max 2) in:

${aws_vpc_endpoint.remote_metastores.*.id[count.index]}

```

**Comment by mroark-exp** [comment]
I pulled down my tfstate file and it does indeed have 3 aws_vpc_endpoint.remote_metastores in it, so I can't figure out what it's complaining about.

**Comment by mroark-exp** [comment]
Ah, this is because one of the vpc endpoints has actually ceased to exist.
